include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    directives_ordering: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    implementation_imports:
      package: true
    prefer_const_constructors: true
