name: core
description: "A package with core resources and utilities"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.7.0
  dio: 5.4.3+1
  pretty_dio_logger: 1.3.1
  geolocator: 12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.3

flutter:

